# Generated by Django 5.2.9 on 2026-01-05 12:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.CharField(default='default', max_length=64)),
                ('model', models.CharField(default='default', max_length=128)),
                ('top_k', models.PositiveSmallIntegerField(default=5)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['deleted', '-updated_at'], name='rag_convers_deleted_1fa627_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=16)),
                ('content', models.TextField()),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('client_message_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rag.conversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='rag_message_convers_76e09e_idx'), models.Index(fields=['client_message_id'], name='rag_message_client__09c9f9_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'client_message_id'), name='uq_msg_conversation_client_message_id')],
            },
        ),
    ]
