# Generated by Django 5.2.9 on 2026-01-23 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_id', models.UUIDField(blank=True, null=True)),
                ('client_message_id', models.CharField(blank=True, max_length=64, null=True)),
                ('model_requested', models.CharField(blank=True, max_length=128, null=True)),
                ('model_used', models.CharField(blank=True, max_length=128, null=True)),
                ('fallback_reason', models.CharField(blank=True, max_length=256, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('ok', models.BooleanField(default=True)),
                ('status_code', models.IntegerField(default=200)),
                ('error_type', models.CharField(blank=True, max_length=128, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('embed_ms', models.IntegerField(default=0)),
                ('qdrant_ms', models.IntegerField(default=0)),
                ('minio_ms', models.IntegerField(default=0)),
                ('llm_ms', models.IntegerField(default=0)),
                ('total_ms', models.IntegerField(default=0)),
                ('api_pre_rag_ms', models.IntegerField(default=0)),
                ('api_post_rag_ms', models.IntegerField(default=0)),
                ('api_total_ms', models.IntegerField(default=0)),
                ('db_ms', models.IntegerField(default=0)),
                ('attachments_total', models.IntegerField(default=0)),
                ('attachments_images', models.IntegerField(default=0)),
                ('attachments_tables', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='rag_ragrequ_created_4e79fe_idx'), models.Index(fields=['conversation_id', 'created_at'], name='rag_ragrequ_convers_4f4b42_idx'), models.Index(fields=['ok', 'created_at'], name='rag_ragrequ_ok_ffe5a7_idx'), models.Index(fields=['model_used', 'created_at'], name='rag_ragrequ_model_u_ebf6cf_idx')],
            },
        ),
    ]
