FROM node:20-bullseye

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

COPY entrypoint-dev.sh /usr/local/bin/entrypoint-dev.sh
RUN chmod +x /usr/local/bin/entrypoint-dev.sh

ENTRYPOINT ["/usr/local/bin/entrypoint-dev.sh"]
CMD ["npm", "run", "dev"]
