# Generated by Django 5.2.9 on 2026-01-07 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_remove_message_extra_conversation_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'image'), ('table', 'table')], max_length=32)),
                ('path', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=127, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='message',
            name='uq_msg_turn_role',
        ),
        migrations.RemoveField(
            model_name='message',
            name='client_id',
        ),
        migrations.AddField(
            model_name='message',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='model',
            field=models.CharField(default='default', max_length=64),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='scope',
            field=models.CharField(blank=True, default='default', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='client_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('conversation', 'role', 'client_message_id'), name='uniq_conv_role_client_mid'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='conversations.message'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('message', 'kind', 'path'), name='uniq_msg_kind_path'),
        ),
    ]
