# Generated by Django 5.2.9 on 2026-01-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_attachment_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='doc_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='model',
            field=models.CharField(default='default', max_length=128),
        ),
    ]
