# Generated by Django 5.2.9 on 2026-01-18 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_doc_ids_alter_conversation_model'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.conversation')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='conversations', through='conversations.ConversationDocument', to='documents.document'),
        ),
        migrations.AddConstraint(
            model_name='conversationdocument',
            constraint=models.UniqueConstraint(fields=('conversation', 'document'), name='uniq_conversation_document'),
        ),
    ]
